// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetReceivedNotifications():Promise<Array<Record<string, any>>>;

export function GetSentNotifications():Promise<Array<Record<string, any>>>;

export function SendNotification(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
