// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetReceivedNotifications() {
  return window['go']['main']['App']['GetReceivedNotifications']();
}

export function GetSentNotifications() {
  return window['go']['main']['App']['GetSentNotifications']();
}

export function SendNotification(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2, arg3, arg4);
}
